# Site settings
title: EchoHollow Labs
description: Stealth Research Division â€” Malware | C2 | Reverse Engineering
baseurl: ""
url: "https://echohollow.github.io"
theme: jekyll-theme-slate
markdown: kramdown

# Social links
github_username: echohollow

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .git/
  - README.md
